ln -sf ~/.config/.bash_profile ~
ln -sf ~/.config/.bashrc ~
ln -sf ~/.config/.bash_functions ~
ln -sf ~/.config/.zprofile ~
ln -sf ~/.config/.latexmk ~
ln -sf ~/.config/.fzf.bash ~
ln -sf ~/.config/.fzf.zsh ~
ln -sf ~/.config/.gitconfig ~
ln -sf ~/.config/.yabairc ~
ln -sf ~/.config/.skhdrc ~
