# lazy reading

#-----------------------------------------
# fzf
#-----------------------------------------
[[plugins]]
repo = 'junegunn/fzf.vim'
on_path = ['.*']
hook_source = '''
    let g:fzf_action = { 'enter': 'tab split' }
    let g:fzf_buffers_jump = 1
    let g:fzf_tags_command = 'ctags -R ./.git/tags .'
    command! -bang -nargs=? -complete=dir Files
      \ call fzf#vim#files(<q-args>, fzf#vim#with_preview(), <bang>0)
    command! -bang -nargs=* Rg
      \ call fzf#vim#grep(
      \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
      \   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))
'''

# yankee
[[plugins]]
repo = 'n04ln/yankee.vim'
on_path = ['.*']
hook_source = '''
    let g:yankee_buf_list = ['"b', '"c', '"x', '"h', '"z']
    vnoremap <silent> Y :call yankee#yank()<CR>
    nnoremap <silent> P :call yankee#paste()<CR>
'''

#-----------------------------------------
# coc
#-----------------------------------------
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'
on_path = ['.*']
hook_source = '''
source /Users/yamagishiryu/.config/nvim/coc-setting.vim
'''

[[plugins]]
repo = 'kizza/actionmenu.nvim'
on_path = ['.*']
hook_source = '''
source ~/.config/nvim/actionmenu-setting.vim
nnoremap <silent> <Leader>s :call ActionMenuCodeActions()<CR>
'''

#-----------------------------------------
# insertion plugin
#-----------------------------------------
[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_path = ['.*']

[[plugins]]
repo = 'wellle/targets.vim'
on_path = ['.*']
merged = '0'

#-----------------------------------------
# syntax
#-----------------------------------------
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged='0'
on_path = ['.*']
hook_source = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    disable = {
      'markdown'
    }
  },
  indent = {
    enable = true
  },
}
EOF
'''

# [[plugins]]
# repo = 'p00f/nvim-ts-rainbow'
# on_path = ['.*']
# merged = '0'
# depends = ['nvim-treesitter']

# markdown
[[plugins]]
repo = 'godlygeek/tabular'
on_ft=['markdown']

[[plugins]]
repo = 'plasticboy/vim-markdown'
depends = ['tabular']
on_ft=['markdown']
merged = '0'
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
  let g:vim_markdown_conceal = 0
'''
