[[plugins]]
repo = 'Shougo/dein.vim'

# indent highlight
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_color_term = 93
  let g:indentLine_bgcolor_term = 236
  let g:indentLine_char = '¦'
  let g:indentLine_leadingSpaceChar = '.'
  let g:indentLine_leadingSpaceEnabled = 1
'''

# run
[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  nnoremap <silent><Space>r :cclose<CR>:QuickRun<CR>
  au FileType qf nnoremap <silent><buffer>q :quit<CR>
  let g:quickrun_config = {
    \'_' : {
    \  'runner' : 'vimproc',
    \  'runner/vimproc/updatetime' : 40,
    \  'hook/close_buffer/enable_failure' : 1,
    \  'hook/close_quickfix/enable_success' : 1,
    \  'outputter/buffer/split' : ':botright 8sp',
    \  'outputter/error/success' : 'buffer',
    \  'outputter/error/error' : 'quickfix',
    \  'outputter/buffer/into' : '1',
    \  'outputter/quickfix/errorformat': '%f:%l, %m in %f on line %l',
    \  'outputter/buffer/close_on_empty': 1,
    \  'outputter' : 'error',
    \},
    \'tex' : {
    \  'command' : 'latexmk',
    \  'cmdopt' : '-pv',
    \  'exec' : ['%c %o %s']
    \},
    \'cpp' : {
    \ 'command' : 'g++',
    \ 'cmdopt' : '-std=c++11',
    \},
    \}
'''

# preview
[[plugins]]
repo = 'tyru/open-browser.vim'

# git 
[[plugins]]
repo = 'tpope/vim-fugitive'

# search
[[plugins]]
repo = 'nelstrom/vim-visual-star-search'

#-----------------------------------------
# motion
#-----------------------------------------
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  map <Space> <Plug>(easymotion-s2)
  let g:EasyMotion_enter_jump_first = 1
  map <Leader><Leader> <Plug>(easymotion-repeat)
  map  <Leader>f <Plug>(easymotion-bd-f)
  nmap <Leader>f <Plug>(easymotion-overwin-f) <Plug>(easymotion-prefix) 
  nmap <Leader>s <Plug>(easymotion-overwin-s2)
  map <Leader>l <Plug>(easymotion-bd-jk)
  nmap <Leader>l <Plug>(easymotion-overwin-line)
  map  <Leader>w <Plug>(easymotion-bd-w)
  nmap <Leader>w <Plug>(easymotion-overwin-w)
  nmap g/ <Plug>(easymotion-sn)
'''
