[[plugins]]
repo = 'Shougo/dein.vim'

# Color
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  au MyAutoCmd VimEnter * highlight Comment ctermfg=63
  au MyAutoCmd VimEnter * highlight Visual ctermfg=236
  au MyAutoCmd VimEnter * highlight MatchParen ctermfg=226 ctermbg=24
  au MyAutoCmd VimEnter * highlight Cursor ctermfg=2
  au MyAutoCmd VimEnter * highlight Special ctermfg=225
  au MyAutoCmd VimEnter * highlight Directory ctermfg=227
  au MyAutoCmd VimEnter * highlight Search ctermbg=5
'''

# deoplete
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:python_host_prog = '$HOME/Library/Python/2.7/bin/:$PATH'
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" : "\<tab>"
'''

# deoplete rust
[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = 'rust'
depends = ['deoplete.nvim']
hook_source = '''
    let g:deoplete#sources#rust#rust_source_path='{$(rustc --print sysroot)/lib/rustlib/src/rust/srcを書く}'
    let g:deoplete#sources#rust#show_duplicates=1
    let g:deoplete#sources#rust#disable_keymap=1
    nmap <buffer> gd <plug>DeopleteRustGoToDefinitionDefault
    nmap <buffer> K  <plug>DeopleteRustShowDocumentation
'''

#indent hilight
[[plugins]]
repo = 'Yggdroot/indentLine'

# run
[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  nnoremap <silent><Space>r :cclose<CR>:QuickRun<CR>
  au FileType qf nnoremap <silent><buffer>q :quit<CR>
  let g:quickrun_config = {
    \'_' : {
    \  'runner' : 'vimproc',
    \  'runner/vimproc/updatetime' : 40,
    \  'hook/close_buffer/enable_failure' : 1,
    \  'hook/close_quickfix/enable_success' : 1,
    \  'outputter/buffer/split' : ':botright 8sp',
    \  'outputter/error/success' : 'buffer',
    \  'outputter/error/error' : 'quickfix',
    \  'outputter/buffer/into' : '1',
    \  'outputter/quickfix/errorformat': '%f:%l, %m in %f on line %l',
    \  'outputter/buffer/close_on_empty': 1,
    \  'outputter' : 'error',
    \},
    \'tex' : {
    \  'command' : 'latexmk',
    \  'cmdopt' : '-pv',
    \  'exec' : ['%c %o %s']
    \},
    \'cpp' : {
    \ 'command' : 'g++',
    \ 'cmdopt' : '-std=c++11',
    \},
    \}
'''

# preview
[[plugins]]
repo = 'tyru/open-browser.vim'

# search
[[plugins]]
repo = 'nelstrom/vim-visual-star-search'

#syntax
##tex
[[plugins]]
repo = 'gi1242/vim-tex-syntax'

#git 
[[plugins]]
repo = 'tpope/vim-fugitive' 

# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# markdown
[[plugins]]
repo = 'gabrielelana/vim-markdown'

[[plugins]]
repo = 'rhysd/nyaovim-markdown-preview'

# rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
  let g:rustfmt_autosave = 1
'''
